##begin config
basename IEAudio
version 1.0
residentpri 0
libbasetype struct IEAudioBase
options noexpunge
##end config

##begin cdef
#include <devices/ahi.h>
#include <libraries/ahi_sub.h>
##end cdef

##begin cdefprivate
#include "DriverData.h"
##end cdefprivate

##begin functionlist
ULONG AHIsub_AllocAudio(struct TagItem *tagList, struct AHIAudioCtrlDrv *AudioCtrl) (A1, A2)
void AHIsub_FreeAudio(struct AHIAudioCtrlDrv *AudioCtrl) (A2)
void AHIsub_Disable(struct AHIAudioCtrlDrv *AudioCtrl) (A2)
void AHIsub_Enable(struct AHIAudioCtrlDrv *AudioCtrl) (A2)
ULONG AHIsub_Start(ULONG Flags, struct AHIAudioCtrlDrv *AudioCtrl) (D0, A2)
ULONG AHIsub_Update(ULONG Flags, struct AHIAudioCtrlDrv *AudioCtrl) (D0, A2)
void AHIsub_Stop(ULONG Flags, struct AHIAudioCtrlDrv *AudioCtrl) (D0, A2)
ULONG AHIsub_SetVol(UWORD Channel, LONG Volume, LONG Pan, struct AHIAudioCtrlDrv *AudioCtrl, ULONG Flags) (D0, D1, D2, A2, D3)
ULONG AHIsub_SetFreq(UWORD Channel, ULONG Freq, struct AHIAudioCtrlDrv *AudioCtrl, ULONG Flags) (D0, D1, A2, D2)
ULONG AHIsub_SetSound(UWORD Channel, UWORD Sound, ULONG Offset, LONG Length, struct AHIAudioCtrlDrv *AudioCtrl, ULONG Flags) (D0, D1, D2, D3, A2, D4)
ULONG AHIsub_SetEffect(APTR Effect, struct AHIAudioCtrlDrv *AudioCtrl) (A0, A2)
ULONG AHIsub_LoadSound(UWORD Sound, ULONG Type, APTR Info, struct AHIAudioCtrlDrv *AudioCtrl) (D0, D1, A0, A2)
void AHIsub_UnloadSound(UWORD Sound, struct AHIAudioCtrlDrv *AudioCtrl) (D0, A2)
IPTR AHIsub_GetAttr(ULONG Attribute, LONG Argument, IPTR DefValue, struct TagItem *tagList, struct AHIAudioCtrlDrv *AudioCtrl) (D0, D1, D2, A1, A2)
LONG AHIsub_HardwareControl(ULONG Attribute, LONG Argument, struct AHIAudioCtrlDrv *AudioCtrl) (D0, D1, A2)
##end functionlist
