##begin config
basename	IEGfx
libbasetype	struct IEGfxBase
version		1.0
residentpri     9
classptr_field  vsd.iegfxclass
classdatatype	struct IEGfx_data
classid         CLID_Hidd_Gfx_IE
superclass      CLID_Hidd_Gfx
##end config

##begin cdefprivate
#include "iegfx_hidd.h"
#include "iegfx_bitmap.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
.interface Hidd_Gfx
CreateObject
Show
CopyBox
##end methodlist


##begin class
##begin config
basename IEBitMap
type hidd
classptr_field vsd.bmclass
superclass CLID_Hidd_ChunkyBM
classdatatype struct IEGfxBitmapData
##end config

##begin methodlist
.interface Root
New
Dispose
Get
##end methodlist
##end class
