#!/usr/bin/env python3

""" This script is used to generate built-in string tables for dos.library.
They use a very own format which is impossible to generate with FlexCat.

Usage:
    genstrings.py dos.cd             # generates errorlist.h (error string table)
    genstrings.py --strings-h dos.cd # generates strings.h  (CATCOMP_NUMBERS header)
"""

import sys

def getline(fhandle):
    line = ";"
    while line.startswith(';'):
        line = fhandle.readline()

    return line.rstrip('\n')


def parse_catalog(path):
    """Parse a .cd catalog file and return (ids, numbers, strings) lists."""
    fhandle = open(path, 'r')
    ids = []
    numbers = []
    strings = []
    while True:
        id_line = getline(fhandle)
        str_line = getline(fhandle)
        if (id_line == "") or (str_line == ""):
            break

        tmp = id_line.split()
        ids.append(tmp[0])

        tmp = tmp[1].split('(')
        tmp = tmp[1].split('/')
        numbers.append(tmp[0])

        strings.append(str_line)
    fhandle.close()
    return ids, numbers, strings


def gen_errorlist(ids, numbers, strings):
    """Generate errorlist.h — the error string table."""
    print("/* This file is automatically generated! Do not edit! */")
    print()

    print("/*")
    print(" * Error codes index table.")
    print(" * This table actually consists of pairs of values (begin, end).")
    print(" * One string in the table below corresponds to one error code")
    print(" * from the specified interval.")
    print(" * The table is terminated by two zeros.")
    print(" * This layout was recreated based on locale.library code brought from MorphOS.")
    print(" */")
    print("const ULONG err_Numbers[] =")
    print("{")
    first = ids[0]
    last = ids[0]
    n = 0
    while n < len(numbers) - 1:
        prev = int(numbers[n])
        n = n + 1
        if int(numbers[n]) == prev + 1:
            last = ids[n]
        else:
            print("    %s, %s," % (first, last))
            first = ids[n]
            last = ids[n]
    print("    0, 0")
    print("};")
    print()

    print("/*")
    print(" * Strings follow each other.")
    print(" * Every string is prefixed by length byte in BCPL manner. NULL terminator is counted too.")
    print(" */")
    print("const char err_Strings[] =")
    print("{")
    for str_line in strings:
        print("    %d," % (len(str_line) + 1))
        for c in str_line:
            print("'%s'," % c, end=' ')
        print("0,")
    print("};")


def gen_strings_h(ids, numbers, strings):
    """Generate strings.h — the CATCOMP_NUMBERS header."""
    print("/* This file is automatically generated from dos.cd. Do not edit! */")
    print()
    print("#ifndef DOS_STRINGS_H")
    print("#define DOS_STRINGS_H")
    print()
    print("#ifndef EXEC_TYPES_H")
    print("#include <exec/types.h>")
    print("#endif")
    print()
    print("#ifdef CATCOMP_ARRAY")
    print("#undef CATCOMP_NUMBERS")
    print("#undef CATCOMP_STRINGS")
    print("#define CATCOMP_NUMBERS")
    print("#define CATCOMP_STRINGS")
    print("#endif")
    print()
    print("#ifdef CATCOMP_BLOCK")
    print("#undef CATCOMP_STRINGS")
    print("#define CATCOMP_STRINGS")
    print("#endif")
    print()
    print("/***************************************************************/")
    print()
    print("#ifdef CATCOMP_NUMBERS")
    print()
    for name, num in zip(ids, numbers):
        print("#define %s %s" % (name, num))
    print()
    print("#endif /* CATCOMP_NUMBERS */")
    print()
    print("#endif /* DOS_STRINGS_H */")


def main():
    mode = "errorlist"
    args = sys.argv[1:]
    if args and args[0] == "--strings-h":
        mode = "strings"
        args = args[1:]

    if not args:
        print("Usage: genstrings.py [--strings-h] <dos.cd>", file=sys.stderr)
        sys.exit(1)

    ids, numbers, strings = parse_catalog(args[0])

    if mode == "strings":
        gen_strings_h(ids, numbers, strings)
    else:
        gen_errorlist(ids, numbers, strings)


if __name__ == "__main__":
    main()
