##begin config
basename        IEHandler
residentpri     -49
handler_func    IEHandlerMain
version         1.0
##end config

##begin cdefprivate
#include "handler.h"
##end cdefprivate

##begin handler
.stacksize 8192
.priority 5
.bootpri -5
DosNode=IE
##end handler
